# Generated by Django 4.2.27 on 2026-01-28 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_no', models.CharField(max_length=50, unique=True, verbose_name='举报编号')),
                ('report_type', models.CharField(choices=[('letter', '来信'), ('visit', '来访'), ('call', '来电'), ('network', '网络举报'), ('other', '其他')], default='letter', max_length=20, verbose_name='举报方式')),
                ('report_level', models.CharField(choices=[('normal', '一般'), ('important', '重要'), ('urgent', '紧急')], default='normal', max_length=20, verbose_name='举报级别')),
                ('reporter_name', models.CharField(blank=True, max_length=100, verbose_name='举报人姓名')),
                ('reporter_phone', models.CharField(blank=True, max_length=20, verbose_name='举报人电话')),
                ('reporter_id_card', models.CharField(blank=True, max_length=18, verbose_name='举报人身份证号')),
                ('is_anonymous', models.BooleanField(default=False, verbose_name='是否匿名')),
                ('accused_name', models.CharField(max_length=100, verbose_name='被举报人姓名')),
                ('accused_unit', models.CharField(blank=True, max_length=200, verbose_name='被举报人单位')),
                ('accused_position', models.CharField(blank=True, max_length=100, verbose_name='被举报人职务')),
                ('title', models.CharField(max_length=200, verbose_name='举报标题')),
                ('content', models.TextField(verbose_name='举报内容')),
                ('attachment', models.FileField(blank=True, upload_to='reports/', verbose_name='附件')),
                ('status', models.CharField(choices=[('pending', '待受理'), ('accepted', '已受理'), ('investigating', '调查中'), ('closed', '已办结'), ('rejected', '不予受理')], default='pending', max_length=20, verbose_name='状态')),
                ('accept_time', models.DateTimeField(blank=True, null=True, verbose_name='受理时间')),
                ('handle_time', models.DateTimeField(blank=True, null=True, verbose_name='办理时间')),
                ('result', models.TextField(blank=True, verbose_name='处理结果')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '信访举报',
                'verbose_name_plural': '信访举报',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_unit', models.CharField(max_length=100, verbose_name='移送单位')),
                ('to_unit', models.CharField(max_length=100, verbose_name='接收单位')),
                ('transfer_reason', models.TextField(verbose_name='移送原因')),
                ('transfer_time', models.DateTimeField(auto_now_add=True, verbose_name='移送时间')),
                ('transfer_person', models.CharField(max_length=50, verbose_name='移送人')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='reports.report', verbose_name='举报件')),
            ],
            options={
                'verbose_name': '移送记录',
                'verbose_name_plural': '移送记录',
            },
        ),
    ]
