# Generated by Django 4.2.29 on 2026-03-11 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('pending', '待受理'), ('accepted', '已受理'), ('investigating', '调查中'), ('closed', '已办结'), ('rejected', '不予受理'), ('recycled', '回收箱')], default='pending', max_length=20, verbose_name='状态'),
        ),
    ]
