# Generated by Django 4.2.29 on 2026-03-11 03:19

from django.db import migrations, models


def update_call_to_phone(apps, schema_editor):
    """将已有的 'call' 类型更新为 'phone'"""
    Report = apps.get_model('reports', 'Report')
    Report.objects.filter(report_type='call').update(report_type='phone')


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_report_status'),
    ]

    operations = [
        # 先执行数据迁移
        migrations.RunPython(update_call_to_phone, reverse_code=migrations.RunPython.noop),
        # 再修改字段定义
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('letter', '来信'), ('visit', '来访'), ('phone', '来电'), ('network', '网络举报'), ('other', '其他')], default='letter', max_length=20, verbose_name='举报方式'),
        ),
    ]
