# Generated by Django 4.2.27 on 2026-01-28 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='消息标题')),
                ('content', models.TextField(verbose_name='消息内容')),
                ('msg_type', models.CharField(choices=[('task', '任务通知'), ('system', '系统通知'), ('remind', '提醒通知')], default='system', max_length=20, verbose_name='消息类型')),
                ('priority', models.CharField(choices=[('low', '一般'), ('medium', '重要'), ('high', '紧急')], default='low', max_length=20, verbose_name='优先级')),
                ('sender', models.CharField(default='系统', max_length=100, verbose_name='发送人')),
                ('is_read', models.BooleanField(default=False, verbose_name='是否已读')),
                ('read_time', models.DateTimeField(blank=True, null=True, verbose_name='阅读时间')),
                ('related_type', models.CharField(blank=True, max_length=50, verbose_name='关联类型')),
                ('related_id', models.CharField(blank=True, max_length=50, verbose_name='关联ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '消息',
                'verbose_name_plural': '消息',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='模板名称')),
                ('msg_type', models.CharField(choices=[('task', '任务通知'), ('system', '系统通知'), ('remind', '提醒通知')], max_length=20, verbose_name='消息类型')),
                ('title_template', models.CharField(max_length=200, verbose_name='标题模板')),
                ('content_template', models.TextField(verbose_name='内容模板')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '消息模板',
                'verbose_name_plural': '消息模板',
            },
        ),
    ]
