# Generated by Django 4.2.27 on 2026-01-28 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_no', models.CharField(max_length=50, unique=True, verbose_name='案件编号')),
                ('case_name', models.CharField(max_length=200, verbose_name='案件名称')),
                ('stage', models.CharField(choices=[('filing', '立案'), ('investigation', '调查'), ('trial', '审理'), ('conclusion', '结案')], default='filing', max_length=20, verbose_name='案件阶段')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('active', '进行中'), ('completed', '已完成'), ('suspended', '已暂停')], default='pending', max_length=20, verbose_name='状态')),
                ('case_level', models.CharField(choices=[('minor', '轻微'), ('ordinary', '一般'), ('major', '严重'), ('serious', '特别严重')], default='ordinary', max_length=20, verbose_name='案件级别')),
                ('suspect_name', models.CharField(max_length=100, verbose_name='被调查人姓名')),
                ('suspect_unit', models.CharField(blank=True, max_length=200, verbose_name='被调查人单位')),
                ('suspect_position', models.CharField(blank=True, max_length=100, verbose_name='被调查人职务')),
                ('suspect_id_card', models.CharField(blank=True, max_length=18, verbose_name='身份证号')),
                ('report_source', models.CharField(blank=True, max_length=100, verbose_name='线索来源')),
                ('report_id', models.CharField(blank=True, max_length=50, verbose_name='来源举报ID')),
                ('summary', models.TextField(blank=True, verbose_name='案件摘要')),
                ('illegal_content', models.TextField(blank=True, verbose_name='违纪违法事实')),
                ('involved_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='涉案金额')),
                ('recovered_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='追回金额')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('filing_date', models.DateField(blank=True, null=True, verbose_name='立案日期')),
                ('filing_approval', models.CharField(blank=True, max_length=100, verbose_name='立案审批人')),
                ('investigation_start_date', models.DateField(blank=True, null=True, verbose_name='调查开始日期')),
                ('investigation_end_date', models.DateField(blank=True, null=True, verbose_name='调查结束日期')),
                ('trial_start_date', models.DateField(blank=True, null=True, verbose_name='审理开始日期')),
                ('trial_end_date', models.DateField(blank=True, null=True, verbose_name='审理结束日期')),
                ('trial_opinion', models.TextField(blank=True, verbose_name='审理意见')),
                ('conclusion_date', models.DateField(blank=True, null=True, verbose_name='结案日期')),
                ('punishment_type', models.CharField(blank=True, max_length=100, verbose_name='处分类型')),
                ('punishment_content', models.TextField(blank=True, verbose_name='处分内容')),
                ('conclusion_report', models.TextField(blank=True, verbose_name='结案报告')),
            ],
            options={
                'verbose_name': '案件',
                'verbose_name_plural': '案件',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_type', models.CharField(choices=[('document', '书证'), ('material', '物证'), ('testimony', '证人证言'), ('statement', '当事人陈述'), ('appraisal', '鉴定意见'), ('audio_video', '视听资料'), ('electronic', '电子数据'), ('other', '其他')], default='document', max_length=20, verbose_name='证据类型')),
                ('name', models.CharField(max_length=200, verbose_name='证据名称')),
                ('description', models.TextField(blank=True, verbose_name='证据描述')),
                ('file', models.FileField(blank=True, upload_to='evidence/', verbose_name='证据文件')),
                ('page_count', models.IntegerField(default=0, verbose_name='页数')),
                ('submitter', models.CharField(blank=True, max_length=100, verbose_name='提交人')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='cases.case', verbose_name='案件')),
            ],
            options={
                'verbose_name': '证据',
                'verbose_name_plural': '证据',
            },
        ),
        migrations.CreateModel(
            name='CaseProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_type', models.CharField(choices=[('filing', '立案'), ('investigation', '调查'), ('trial', '审理'), ('conclusion', '结案')], max_length=20, verbose_name='进度类型')),
                ('progress_date', models.DateField(verbose_name='进度日期')),
                ('progress_content', models.TextField(verbose_name='进度内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresses', to='cases.case', verbose_name='案件')),
            ],
            options={
                'verbose_name': '案件进度',
                'verbose_name_plural': '案件进度',
                'ordering': ['-progress_date'],
            },
        ),
    ]
