# Generated by Django 4.2.27 on 2026-01-28 04:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='caseprogress',
            name='handler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='处理人'),
        ),
        migrations.AddField(
            model_name='case',
            name='investigators',
            field=models.ManyToManyField(related_name='investigated_cases', to=settings.AUTH_USER_MODEL, verbose_name='调查人员'),
        ),
        migrations.AddField(
            model_name='case',
            name='leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_cases', to=settings.AUTH_USER_MODEL, verbose_name='主办人'),
        ),
    ]
