# Generated by Django 4.2.27 on 2026-01-28 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accept_no', models.CharField(max_length=50, unique=True, verbose_name='受理编号')),
                ('department', models.CharField(blank=True, max_length=200, verbose_name='移送部门')),
                ('accept_date', models.DateField(verbose_name='受理日期')),
                ('deadline', models.IntegerField(default=30, verbose_name='审理期限(天)')),
                ('judge', models.CharField(max_length=100, verbose_name='主办审理员')),
                ('assistants', models.CharField(blank=True, max_length=500, verbose_name='协办人员')),
                ('status', models.CharField(choices=[('pending', '待审理'), ('processing', '审理中'), ('completed', '已审结')], default='pending', max_length=20, verbose_name='审理状态')),
                ('trial_opinion', models.TextField(blank=True, verbose_name='审理意见')),
                ('result', models.CharField(blank=True, max_length=200, verbose_name='审理结果')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trials', to='cases.case', verbose_name='关联案件')),
            ],
            options={
                'verbose_name': '案件审理',
                'verbose_name_plural': '案件审理',
                'ordering': ['-accept_date'],
            },
        ),
        migrations.CreateModel(
            name='Conclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conclusion_no', models.CharField(max_length=50, unique=True, verbose_name='结案编号')),
                ('conclusion_date', models.DateField(verbose_name='结案日期')),
                ('conclusion_type', models.CharField(choices=[('party_discipline', '党纪处分'), ('administrative', '政务处分'), ('judicial', '移送司法'), ('criticism', '批评教育'), ('concluded', '予以了结')], max_length=50, verbose_name='结案方式')),
                ('decision', models.TextField(blank=True, verbose_name='处分决定')),
                ('execution_status', models.CharField(choices=[('pending', '执行中'), ('completed', '已执行')], default='pending', max_length=20, verbose_name='执行状态')),
                ('execute_date', models.DateField(blank=True, null=True, verbose_name='执行日期')),
                ('summary', models.TextField(blank=True, verbose_name='案件总结')),
                ('archived', models.BooleanField(default=False, verbose_name='是否归档')),
                ('archived_date', models.DateField(blank=True, null=True, verbose_name='归档日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conclusions', to='cases.case', verbose_name='关联案件')),
            ],
            options={
                'verbose_name': '结案报告',
                'verbose_name_plural': '结案报告',
                'ordering': ['-conclusion_date'],
            },
        ),
    ]
