# Generated by Django 4.2.27 on 2026-01-28 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_trial_conclusion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evidence',
            options={'ordering': ['-created_at'], 'verbose_name': '证据', 'verbose_name_plural': '证据'},
        ),
    ]
