# Generated by Django 4.2.27 on 2026-02-08 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_alter_evidence_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='case_category',
            field=models.CharField(choices=[('discipline', '纪律审查'), ('supervision', '监督执纪'), ('case', '简易案件')], default='discipline', max_length=20, verbose_name='案件类型'),
        ),
    ]
