# Generated by Django 4.2.27 on 2026-02-08 17:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cases', '0005_case_case_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistPartyTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_no', models.CharField(max_length=50, unique=True, verbose_name='任务编号')),
                ('task_name', models.CharField(max_length=200, verbose_name='任务名称')),
                ('owner', models.CharField(max_length=100, verbose_name='负责人')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='截止日期')),
                ('status', models.IntegerField(choices=[(0, '待开始'), (1, '进行中'), (2, '已完成'), (3, '已逾期')], default=0, verbose_name='状态')),
                ('progress', models.IntegerField(default=0, verbose_name='进度(%)')),
                ('description', models.TextField(blank=True, verbose_name='任务描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '协助党委任务',
                'verbose_name_plural': '协助党委任务',
                'ordering': ['-created_at'],
            },
        ),
    ]
