# Generated by Django 4.2.27 on 2026-02-09 03:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cases', '0006_assistpartytask'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supervision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='检查标题')),
                ('supervision_type', models.CharField(choices=[('routine', '例行检查'), ('special', '专项检查'), ('random', '随机抽查')], max_length=20, verbose_name='检查类型')),
                ('content', models.TextField(blank=True, verbose_name='检查内容')),
                ('target_objects', models.TextField(blank=True, verbose_name='检查对象')),
                ('status', models.CharField(choices=[('planned', '计划中'), ('active', '进行中'), ('completed', '已完成'), ('reported', '已报告')], default='planned', max_length=20, verbose_name='状态')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='开始日期')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='结束日期')),
                ('progress', models.IntegerField(default=0, verbose_name='进度(%)')),
                ('result', models.TextField(blank=True, verbose_name='检查结果')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervision_leader', to=settings.AUTH_USER_MODEL, verbose_name='负责人')),
                ('members', models.ManyToManyField(blank=True, related_name='supervision_members', to=settings.AUTH_USER_MODEL, verbose_name='参与人员')),
            ],
            options={
                'verbose_name': '监督检查',
                'verbose_name_plural': '监督检查',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Regulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='法规标题')),
                ('category', models.CharField(choices=[('law', '法律'), ('regulation', '法规'), ('rule', '规章'), ('policy', '规范性文件'), ('interpretation', '解释')], max_length=20, verbose_name='法规类型')),
                ('document_no', models.CharField(blank=True, max_length=100, verbose_name='法规文号')),
                ('issuing_authority', models.CharField(blank=True, max_length=200, verbose_name='发布部门')),
                ('level', models.CharField(blank=True, choices=[('national', '国家级'), ('provincial', '省级'), ('city', '市级'), ('district', '区县级')], max_length=20, verbose_name='效力层级')),
                ('content', models.TextField(blank=True, verbose_name='法规内容')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='regulations/', verbose_name='附件')),
                ('publish_date', models.DateField(blank=True, null=True, verbose_name='发布日期')),
                ('effective_date', models.DateField(blank=True, null=True, verbose_name='施行日期')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='失效日期')),
                ('is_valid', models.BooleanField(default=True, verbose_name='是否有效')),
                ('view_count', models.IntegerField(default=0, verbose_name='浏览次数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '法规',
                'verbose_name_plural': '法规库',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EducationMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='资料标题')),
                ('category', models.CharField(choices=[('policy', '政策法规'), ('case', '典型案例'), ('notice', '通知公告'), ('study', '学习材料')], max_length=20, verbose_name='资料类型')),
                ('content', models.TextField(blank=True, verbose_name='内容')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='education/', verbose_name='附件')),
                ('source', models.CharField(blank=True, max_length=200, verbose_name='来源')),
                ('view_count', models.IntegerField(default=0, verbose_name='浏览次数')),
                ('is_published', models.BooleanField(default=True, verbose_name='是否发布')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '教育资料',
                'verbose_name_plural': '教育资料',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EducationActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='活动标题')),
                ('content', models.TextField(blank=True, verbose_name='活动内容')),
                ('activity_type', models.CharField(blank=True, max_length=100, verbose_name='活动类型')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='活动地点')),
                ('participants', models.TextField(blank=True, verbose_name='参与人员')),
                ('status', models.CharField(choices=[('upcoming', '未开始'), ('ongoing', '进行中'), ('completed', '已结束')], default='upcoming', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '教育活动',
                'verbose_name_plural': '教育活动',
                'ordering': ['-created_at'],
            },
        ),
    ]
