# Generated by Django 4.2.27 on 2026-01-29 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='real_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='真实姓名'),
        ),
    ]
