# Generated by Django 4.2.27 on 2026-01-28 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssistParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='工作标题')),
                ('content', models.TextField(verbose_name='工作内容')),
                ('assist_type', models.CharField(max_length=100, verbose_name='协助类型')),
                ('party_organization', models.CharField(max_length=200, verbose_name='党委组织')),
                ('status', models.CharField(choices=[('pending', '待开展'), ('active', '进行中'), ('completed', '已完成')], default='pending', max_length=20, verbose_name='状态')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='开始日期')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='结束日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '协助党委',
                'verbose_name_plural': '协助党委',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Clue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clue_no', models.CharField(max_length=50, unique=True, verbose_name='线索编号')),
                ('source', models.CharField(choices=[('report', '举报线索'), ('audit', '审计线索'), ('discover', '发现线索'), ('transfer', '移送线索'), ('other', '其他')], default='report', max_length=20, verbose_name='线索来源')),
                ('title', models.CharField(max_length=200, verbose_name='线索标题')),
                ('content', models.TextField(verbose_name='线索内容')),
                ('status', models.CharField(choices=[('pending', '待处置'), ('reviewed', '已审阅'), ('assigned', '已分办'), ('investigating', '调查中'), ('closed', '已了结'), ('filed', '已暂存')], default='pending', max_length=20, verbose_name='状态')),
                ('discoverer', models.CharField(blank=True, max_length=100, verbose_name='发现人')),
                ('discover_time', models.DateField(blank=True, null=True, verbose_name='发现时间')),
                ('review_time', models.DateTimeField(blank=True, null=True, verbose_name='审阅时间')),
                ('review_opinion', models.TextField(blank=True, verbose_name='审阅意见')),
                ('handle_time', models.DateTimeField(blank=True, null=True, verbose_name='处置时间')),
                ('handle_result', models.TextField(blank=True, verbose_name='处置结果')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '线索处置',
                'verbose_name_plural': '线索处置',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DisciplineEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('edu_type', models.CharField(choices=[('notice', '通报'), ('study', '学习材料'), ('video', '视频资料'), ('case', '案例警示'), ('exam', '知识测试')], default='study', max_length=20, verbose_name='类型')),
                ('content', models.TextField(verbose_name='内容')),
                ('attachment', models.FileField(blank=True, upload_to='education/', verbose_name='附件')),
                ('target_dept', models.CharField(blank=True, max_length=200, verbose_name='目标部门')),
                ('is_published', models.BooleanField(default=False, verbose_name='是否发布')),
                ('publish_time', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '纪律教育',
                'verbose_name_plural': '纪律教育',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Regulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('category', models.CharField(choices=[('law', '法律'), ('regulation', '法规'), ('rule', '规章'), ('policy', '政策'), ('interpretation', '解释')], default='law', max_length=20, verbose_name='分类')),
                ('document_no', models.CharField(blank=True, max_length=100, verbose_name='文号')),
                ('issuing_authority', models.CharField(blank=True, max_length=200, verbose_name='发文机关')),
                ('content', models.TextField(verbose_name='内容')),
                ('attachment', models.FileField(blank=True, upload_to='regulations/', verbose_name='附件')),
                ('effective_date', models.DateField(blank=True, null=True, verbose_name='生效日期')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='失效日期')),
                ('is_valid', models.BooleanField(default=True, verbose_name='是否有效')),
                ('view_count', models.IntegerField(default=0, verbose_name='浏览次数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '法规库',
                'verbose_name_plural': '法规库',
                'ordering': ['-effective_date'],
            },
        ),
        migrations.CreateModel(
            name='Supervision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('supervision_type', models.CharField(choices=[('routine', '常规检查'), ('special', '专项检查'), ('random', '随机抽查')], default='routine', max_length=20, verbose_name='检查类型')),
                ('content', models.TextField(verbose_name='检查内容')),
                ('target_objects', models.CharField(blank=True, max_length=500, verbose_name='检查对象')),
                ('status', models.CharField(choices=[('planned', '计划中'), ('active', '进行中'), ('completed', '已完成'), ('reported', '已报告')], default='planned', max_length=20, verbose_name='状态')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='开始日期')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='结束日期')),
                ('result', models.TextField(blank=True, verbose_name='检查结果')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '监督检查',
                'verbose_name_plural': '监督检查',
                'ordering': ['-created_at'],
            },
        ),
    ]
