# Generated by Django 4.2.27 on 2026-01-28 04:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervision',
            name='leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_supervisions', to=settings.AUTH_USER_MODEL, verbose_name='负责人'),
        ),
        migrations.AddField(
            model_name='supervision',
            name='members',
            field=models.ManyToManyField(related_name='supervision_tasks', to=settings.AUTH_USER_MODEL, verbose_name='参与人员'),
        ),
        migrations.AddField(
            model_name='disciplineeducation',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='发布人'),
        ),
        migrations.AddField(
            model_name='clue',
            name='handler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_clues', to=settings.AUTH_USER_MODEL, verbose_name='承办人'),
        ),
        migrations.AddField(
            model_name='clue',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_clues', to=settings.AUTH_USER_MODEL, verbose_name='审阅人'),
        ),
        migrations.AddField(
            model_name='assistparty',
            name='handler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='处理人'),
        ),
    ]
